# Array Operations
## Add arrays, Subtract, multiply 
## Scalar operations on array

In [2]:
import numpy as np

x = np.arange(0,10)
y = np.arange(10,20)
x.shape, y.shape

((10,), (10,))

In [3]:
x , y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))

In [4]:
x + y

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
y - x

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [6]:
x * y

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

In [7]:
x / y 

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [8]:
x = np.arange(50).reshape(5,10)
y = np.arange(5)
z = np.arange(10)

x , y , z

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [9]:
x.shape, y.shape, z.shape

((5, 10), (5,), (10,))

In [10]:
x + y # Cant do, error!

ValueError: operands could not be broadcast together with shapes (5,10) (5,) 

In [ ]:
x + z # If

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [30, 32, 34, 36, 38, 40, 42, 44, 46, 48],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

In [ ]:
x * z # Works!

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  0,  11,  24,  39,  56,  75,  96, 119, 144, 171],
       [  0,  21,  44,  69,  96, 125, 156, 189, 224, 261],
       [  0,  31,  64,  99, 136, 175, 216, 259, 304, 351],
       [  0,  41,  84, 129, 176, 225, 276, 329, 384, 441]])

In [ ]:
x * 5 # Works ! scalar operation on an array

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245]])