In [3]:
import numpy as np

mixed1 = np.array([1, 2, 'apples'])
print(mixed1)
mixed2 = np.array([1, 2, 'fruits'])

k = mixed1 + mixed2
print(k)
mixed1.dtype

['1' '2' 'apples']
['11' '22' 'applesfruits']


dtype('<U21')

In [5]:
mixed1.astype(np.int16) # Error since there is a string present

ValueError: invalid literal for int() with base 10: np.str_('apples')

In [4]:
x = np.array([1 , 2 ,3 ,4 ,5]) # all integers 
x.dtype # integer

dtype('int64')

In [5]:
y = x.astype(np.float32) # Convert integer array to float
y

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
y = y+ 0.5 # Add a scalar to a numpy array
z = y.astype(np.int32) # This time floar is rounded into integer
z

array([1, 2, 3, 4, 5], dtype=int32)

In [7]:
strs = np.array([1 ,2 ,3 ,4 ,5], dtype=str) # create and array of strings
strs

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [8]:
bools = np.array([-5, -4, -3, -2, -1, 0, 1 ,2 ,3 ,4 ,5], dtype=bool) # create and array of Boolean values
bools

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

# Note how 0 is False and alll other numbers are True

In [13]:
k = np.random.rand(10,10)
k = k * 10
k = k.astype(np.int32)
k

array([[8, 9, 7, 1, 6, 5, 1, 7, 2, 2],
       [9, 4, 5, 5, 6, 8, 2, 4, 7, 8],
       [2, 8, 1, 9, 6, 4, 1, 4, 1, 6],
       [6, 1, 1, 9, 2, 1, 2, 9, 3, 3],
       [0, 5, 8, 3, 8, 7, 5, 2, 0, 1],
       [0, 7, 2, 1, 1, 3, 2, 1, 1, 5],
       [5, 9, 4, 3, 8, 3, 7, 4, 1, 5],
       [0, 8, 6, 6, 5, 9, 5, 4, 9, 8],
       [3, 8, 2, 5, 8, 2, 9, 0, 2, 3],
       [9, 6, 7, 1, 4, 4, 0, 2, 5, 0]], dtype=int32)

In [14]:
k.squeeze()

array([[8, 9, 7, 1, 6, 5, 1, 7, 2, 2],
       [9, 4, 5, 5, 6, 8, 2, 4, 7, 8],
       [2, 8, 1, 9, 6, 4, 1, 4, 1, 6],
       [6, 1, 1, 9, 2, 1, 2, 9, 3, 3],
       [0, 5, 8, 3, 8, 7, 5, 2, 0, 1],
       [0, 7, 2, 1, 1, 3, 2, 1, 1, 5],
       [5, 9, 4, 3, 8, 3, 7, 4, 1, 5],
       [0, 8, 6, 6, 5, 9, 5, 4, 9, 8],
       [3, 8, 2, 5, 8, 2, 9, 0, 2, 3],
       [9, 6, 7, 1, 4, 4, 0, 2, 5, 0]], dtype=int32)