In [6]:
import numpy as np
x = np.arange(1,101)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
y = x
x[0] = 10000
y # While values of x[0] was changed, y also changed

array([10000,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12,    13,    14,    15,    16,    17,    18,
          19,    20,    21,    22,    23,    24,    25,    26,    27,
          28,    29,    30,    31,    32,    33,    34,    35,    36,
          37,    38,    39,    40,    41,    42,    43,    44,    45,
          46,    47,    48,    49,    50,    51,    52,    53,    54,
          55,    56,    57,    58,    59,    60,    61,    62,    63,
          64,    65,    66,    67,    68,    69,    70,    71,    72,
          73,    74,    75,    76,    77,    78,    79,    80,    81,
          82,    83,    84,    85,    86,    87,    88,    89,    90,
          91,    92,    93,    94,    95,    96,    97,    98,    99,
         100])

In [9]:
y = x[1:10]
y

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
# Now I change x, y still change
x[1] = 2000
y

array([2000,    3,    4,    5,    6,    7,    8,    9,   10])

In [12]:
# How to know if variables are sharing memory?
np.may_share_memory(x, y)

True

In [15]:
# What if is I did this:
y = x[1:10].astype(float)
y

array([2000.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.])

In [16]:
# They dont share memory now!
np.may_share_memory(x , y)

False

In [ ]:
x = np.arange(1,101).reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [23]:
y = x[:]
y.shape

(10, 10)

In [18]:
x.dtype

dtype('int64')

In [24]:
np.may_share_memory(x , y)

True

In [26]:
y = x.reshape(5,20).T
y

array([[  1,  21,  41,  61,  81],
       [  2,  22,  42,  62,  82],
       [  3,  23,  43,  63,  83],
       [  4,  24,  44,  64,  84],
       [  5,  25,  45,  65,  85],
       [  6,  26,  46,  66,  86],
       [  7,  27,  47,  67,  87],
       [  8,  28,  48,  68,  88],
       [  9,  29,  49,  69,  89],
       [ 10,  30,  50,  70,  90],
       [ 11,  31,  51,  71,  91],
       [ 12,  32,  52,  72,  92],
       [ 13,  33,  53,  73,  93],
       [ 14,  34,  54,  74,  94],
       [ 15,  35,  55,  75,  95],
       [ 16,  36,  56,  76,  96],
       [ 17,  37,  57,  77,  97],
       [ 18,  38,  58,  78,  98],
       [ 19,  39,  59,  79,  99],
       [ 20,  40,  60,  80, 100]])

In [28]:
np.may_share_memory(x, y)

True

In [ ]:
# Copy operation prevents memory sharing
y = x.reshape(5,20).T.copy() 
y

array([[  1,  21,  41,  61,  81],
       [  2,  22,  42,  62,  82],
       [  3,  23,  43,  63,  83],
       [  4,  24,  44,  64,  84],
       [  5,  25,  45,  65,  85],
       [  6,  26,  46,  66,  86],
       [  7,  27,  47,  67,  87],
       [  8,  28,  48,  68,  88],
       [  9,  29,  49,  69,  89],
       [ 10,  30,  50,  70,  90],
       [ 11,  31,  51,  71,  91],
       [ 12,  32,  52,  72,  92],
       [ 13,  33,  53,  73,  93],
       [ 14,  34,  54,  74,  94],
       [ 15,  35,  55,  75,  95],
       [ 16,  36,  56,  76,  96],
       [ 17,  37,  57,  77,  97],
       [ 18,  38,  58,  78,  98],
       [ 19,  39,  59,  79,  99],
       [ 20,  40,  60,  80, 100]])

In [30]:
np.may_share_memory(x,y)

False