In [5]:
import numpy as np
x = np.random.rand(10000)
x

array([0.86491354, 0.72698166, 0.00087884, ..., 0.8418878 , 0.06673381,
       0.24611972], shape=(10000,))

In [6]:
# Sum
np.sum(x)

np.float64(5017.412274041813)

In [7]:
# Mean
np.mean(x)

np.float64(0.5017412274041814)

In [8]:
# standard deviation
np.std(x)

np.float64(0.2877192941258973)

In [ ]:
# Max, min
np.max(x), np.min(x)

(np.float64(0.9999802615500495), np.float64(3e-05))

In [12]:
x = np.random.rand(10000)* 100
x

array([75.81875201, 36.71982721,  2.64200922, ...,  8.86133481,
       39.72664012, 81.58436361], shape=(10000,))

In [13]:
x =x.reshape(100,100)
x

array([[75.81875201, 36.71982721,  2.64200922, ..., 84.33984819,
        20.58562426, 91.9182786 ],
       [60.94418107,  3.17419451,  2.0773572 , ..., 75.50082676,
        98.01626763, 71.40144802],
       [65.23636416, 87.38905699, 32.22740652, ..., 54.66034211,
        57.15630991, 18.64667069],
       ...,
       [18.55575601, 97.73682231, 41.00201158, ..., 38.5569013 ,
         7.86865435,  2.48817317],
       [61.17682498, 78.39830095, 47.50712329, ..., 40.01830569,
        12.91027648, 30.081633  ],
       [78.55812267, 10.22827344, 34.25827803, ...,  8.86133481,
        39.72664012, 81.58436361]], shape=(100, 100))

In [ ]:
# Perform columnar addition
np.sum(x, axis=0), x.sum(axis=0) # Both are same

(array([4872.44012579, 4742.4863457 , 5210.62058842, 5119.75557729,
        4701.96707755, 5221.33992934, 4887.04218206, 4692.8322912 ,
        5397.03926589, 4675.13157379, 4926.27062275, 5235.56686086,
        5015.5473023 , 5070.89279829, 4761.66078405, 4866.18051025,
        5018.26085847, 5426.325977  , 4887.58260786, 4759.87801021,
        4694.44056492, 4974.65561304, 4617.10283863, 4948.13559139,
        5005.93608555, 4971.90217212, 4664.64126691, 5535.72772729,
        4624.37019259, 5075.40481038, 5243.0653912 , 5185.76694324,
        5111.41063805, 4774.65390253, 5194.29650164, 5150.18900471,
        5344.00029547, 5090.38173471, 5147.14771916, 4940.87051208,
        4570.41829962, 4694.59380328, 5356.91630825, 4828.87887183,
        4944.55645745, 4537.06051304, 5071.10071446, 5262.80876542,
        5365.90394168, 5189.74575429, 4994.01417785, 5077.5185205 ,
        5284.23682541, 4769.34089846, 5254.57808693, 4383.75722983,
        5465.07298756, 5061.34334311, 5084.35412

In [16]:
# Create a 1D array of numbers from 1 to 10
row_template = np.arange(1, 11)

# Repeat this row 10 times to create a 2D array
array_1_to_10_repeated = np.tile(row_template, (10, 1))

print(array_1_to_10_repeated)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]


In [ ]:
np.sum(array_1_to_10_repeated, axis=0) # Add all columnwise 

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.sum(array_1_to_10_repeated, axis=1) # Add all rowwise

array([55, 55, 55, 55, 55, 55, 55, 55, 55, 55])

In [21]:
array_1_to_10_repeated.sum()

np.int64(550)

In [22]:
array_1_to_10_repeated.mean()

np.float64(5.5)