In [4]:
import numpy as np
import csv

with open("PCOS_Data_without_infertility.csv") as f:
    reader = csv.reader(f)
    data = list(reader)

data

[['Sl. No',
  'Patient File No.',
  'PCOS (Y/N)',
  ' Age (yrs)',
  'Weight (Kg)',
  'Height(Cm) ',
  'BMI',
  'Blood Group',
  'Pulse rate(bpm) ',
  'RR (breaths/min)',
  'Hb(g/dl)',
  'Cycle(R/I)',
  'Cycle length(days)',
  'Marraige Status (Yrs)',
  'Pregnant(Y/N)',
  'No. of aborptions',
  '  I   beta-HCG(mIU/mL)',
  'II    beta-HCG(mIU/mL)',
  'FSH(mIU/mL)',
  'LH(mIU/mL)',
  'FSH/LH',
  'Hip(inch)',
  'Waist(inch)',
  'Waist:Hip Ratio',
  'TSH (mIU/L)',
  'AMH(ng/mL)',
  'PRL(ng/mL)',
  'Vit D3 (ng/mL)',
  'PRG(ng/mL)',
  'RBS(mg/dl)',
  'Weight gain(Y/N)',
  'hair growth(Y/N)',
  'Skin darkening (Y/N)',
  'Hair loss(Y/N)',
  'Pimples(Y/N)',
  'Fast food (Y/N)',
  'Reg.Exercise(Y/N)',
  'BP _Systolic (mmHg)',
  'BP _Diastolic (mmHg)',
  'Follicle No. (L)',
  'Follicle No. (R)',
  'Avg. F size (L) (mm)',
  'Avg. F size (R) (mm)',
  'Endometrium (mm)',
  ''],
 ['1',
  '1',
  '0',
  '28',
  '44.6',
  '152',
  '19.3',
  '15',
  '78',
  '22',
  '10.48',
  '2',
  '5',
  '7',
  '0',
  '

In [5]:
header = data[0]
header

['Sl. No',
 'Patient File No.',
 'PCOS (Y/N)',
 ' Age (yrs)',
 'Weight (Kg)',
 'Height(Cm) ',
 'BMI',
 'Blood Group',
 'Pulse rate(bpm) ',
 'RR (breaths/min)',
 'Hb(g/dl)',
 'Cycle(R/I)',
 'Cycle length(days)',
 'Marraige Status (Yrs)',
 'Pregnant(Y/N)',
 'No. of aborptions',
 '  I   beta-HCG(mIU/mL)',
 'II    beta-HCG(mIU/mL)',
 'FSH(mIU/mL)',
 'LH(mIU/mL)',
 'FSH/LH',
 'Hip(inch)',
 'Waist(inch)',
 'Waist:Hip Ratio',
 'TSH (mIU/L)',
 'AMH(ng/mL)',
 'PRL(ng/mL)',
 'Vit D3 (ng/mL)',
 'PRG(ng/mL)',
 'RBS(mg/dl)',
 'Weight gain(Y/N)',
 'hair growth(Y/N)',
 'Skin darkening (Y/N)',
 'Hair loss(Y/N)',
 'Pimples(Y/N)',
 'Fast food (Y/N)',
 'Reg.Exercise(Y/N)',
 'BP _Systolic (mmHg)',
 'BP _Diastolic (mmHg)',
 'Follicle No. (L)',
 'Follicle No. (R)',
 'Avg. F size (L) (mm)',
 'Avg. F size (R) (mm)',
 'Endometrium (mm)',
 '']

In [6]:
data = np.array(data[1:])
data

array([['1', '1', '0', ..., '18', '8.5', ''],
       ['2', '2', '0', ..., '14', '3.7', ''],
       ['3', '3', '1', ..., '20', '10', ''],
       ...,
       ['', '', '', ..., '', '', ''],
       ['', '', '', ..., '', '', ''],
       ['', '', '', ..., '', '', '']], shape=(999, 45), dtype='<U8')

In [14]:
age = data[:, 4]
age[age == ""] = "0"
age = age.astype(np.float32)
age

array([ 44.6,  65. ,  68.8,  65. ,  52. ,  74.1,  64. ,  58.5,  40. ,
        52. ,  71. ,  49. ,  74. ,  50. ,  57.3,  80.5,  43. ,  69.2,
        52.4,  85. ,  64. ,  50. ,  64.2,  65. ,  63. ,  42. ,  76. ,
        68. ,  62. ,  56. ,  50. ,  57. ,  58. ,  54. ,  50. ,  71. ,
        73. ,  72. ,  53. ,  74. ,  40. ,  78. ,  33. ,  68. ,  59. ,
        56. ,  75. ,  40. ,  51. ,  51. ,  68. ,  54. ,  50. ,  62. ,
        58. ,  68. ,  56. ,  58. ,  75. ,  67. ,  63. ,  76. ,  60. ,
        55. ,  56. ,  71. ,  56. ,  62. ,  55. ,  65. ,  54. ,  61. ,
        65. ,  70. ,  59. ,  72. ,  43. ,  52. ,  48. , 108. ,  57.6,
        60. ,  52. ,  43.7,  60. ,  61.6,  64. ,  56. ,  69.5,  65. ,
        74.4,  45. ,  83.5,  52. ,  62.5,  50. ,  67.5,  91.4,  61. ,
        61.7,  62.2,  74.1,  64.3,  57. ,  60. ,  68.6,  60. ,  54. ,
        53. ,  80. ,  59. ,  75. ,  71.2,  63. ,  74. ,  67. ,  63. ,
        68. ,  83. ,  55. ,  63. ,  48. ,  79. ,  40. ,  78. ,  54. ,
        56. ,  48. ,

In [16]:
old_people = age > 70

old_people

array([False, False, False, False, False,  True, False, False, False,
       False,  True, False,  True, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
        True,  True, False,  True, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False,  True,  True, False,  True, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,

In [18]:
old_people_data = age[old_people]
old_people_data

array([ 74.1,  71. ,  74. ,  80.5,  85. ,  76. ,  71. ,  73. ,  72. ,
        74. ,  78. ,  75. ,  75. ,  76. ,  71. ,  72. , 108. ,  74.4,
        83.5,  91.4,  74.1,  80. ,  75. ,  71.2,  74. ,  83. ,  79. ,
        78. ,  89. ,  71. ,  85. ,  72. ,  72.3,  73.5,  78. ,  89. ,
        88. ,  76. ,  80. ,  83. ,  71. ,  72. ,  76.8,  75. ,  74.3,
        71. ,  78. , 104. ,  79. ,  85. ,  83. ,  85. ,  72. ,  82. ,
        89. ,  73. ,  85. ,  83. ,  71. ,  80.4,  77.9,  74. ,  76.9,
        74. ,  71.8,  74.1,  71. ,  76. ,  73. ,  72. ,  71.5,  89. ,
        94. ,  87.9,  76.9,  72. ,  78. ,  80. ,  82. ], dtype=float32)