# Data Types
# Different Data Types, Casting, sizes and structure

In [ ]:
# Data types

import numpy as np
# int8
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [3]:
# int32
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [ ]:
# int64. int - Both are same
np.iinfo(np.int64), np.iinfo(int)

(iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64),
 iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64))

In [11]:
# float 
np.finfo(np.float32)

finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)

# Operations on different data types

In [12]:
x = np.arange(0.0, 10.0, 1.0) # creates a float array
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
np.info(x)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x248546ffb50
byteorder:  little
byteswap:  False
type: float64


In [13]:
y = np.arange(10) # created a integer array
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.info(y)

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x248546ffe70
byteorder:  little
byteswap:  False
type: int64


In [ ]:
x + y # We get a float array. Basically integer values have been upcasted to float

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [18]:
y.dtype # y is integer array

dtype('int64')

In [ ]:
# Assigning a floar into a integer array
y[0] = 13.8
y.dtype # Data Type of y stayed same as integer !!

dtype('int64')

In [ ]:
# are you sure?!!
y

array([13,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
# The assigend value has been downcasted to int

## Custom Data Types

In [23]:
datatype = np.dtype([('name',np.str_),('age',np.int8)])
datatype

dtype([('name', '<U'), ('age', 'i1')])