# Array Operations like shape, ravel(), flatten(), reshape(), resize()

In [8]:
import numpy as np

x = np.arange(100)
x, x.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 (100,))

In [3]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
z = np.random.rand(10,10)
z, z.shape

(array([[0.11951592, 0.52452718, 0.17163764, 0.88442747, 0.06137786,
         0.79213121, 0.2027002 , 0.84121977, 0.91072484, 0.20073507],
        [0.28318079, 0.07380053, 0.67700478, 0.72035511, 0.87943068,
         0.29647927, 0.28925387, 0.87919524, 0.94030504, 0.84898947],
        [0.28587904, 0.79406193, 0.72896436, 0.55794227, 0.76490174,
         0.5606896 , 0.97423891, 0.95803352, 0.11273432, 0.39664859],
        [0.86059036, 0.79688046, 0.78497531, 0.43175944, 0.64595988,
         0.78482064, 0.52985417, 0.18770541, 0.97799868, 0.61801055],
        [0.39028889, 0.21912466, 0.03391681, 0.03816693, 0.79938474,
         0.12088361, 0.32074169, 0.82628426, 0.60635327, 0.24390741],
        [0.32615678, 0.86244742, 0.24893153, 0.92328903, 0.23840465,
         0.14403381, 0.7268851 , 0.83539397, 0.48675055, 0.53436309],
        [0.633084  , 0.62792537, 0.16126607, 0.99616922, 0.54788501,
         0.57326428, 0.99641083, 0.61719278, 0.32436429, 0.54942971],
        [0.15553189, 0.0788

In [ ]:
k = z.ravel() # Converts the shape of a multi dimensional arrays to a flat shape
k , k.shape

(array([0.11951592, 0.52452718, 0.17163764, 0.88442747, 0.06137786,
        0.79213121, 0.2027002 , 0.84121977, 0.91072484, 0.20073507,
        0.28318079, 0.07380053, 0.67700478, 0.72035511, 0.87943068,
        0.29647927, 0.28925387, 0.87919524, 0.94030504, 0.84898947,
        0.28587904, 0.79406193, 0.72896436, 0.55794227, 0.76490174,
        0.5606896 , 0.97423891, 0.95803352, 0.11273432, 0.39664859,
        0.86059036, 0.79688046, 0.78497531, 0.43175944, 0.64595988,
        0.78482064, 0.52985417, 0.18770541, 0.97799868, 0.61801055,
        0.39028889, 0.21912466, 0.03391681, 0.03816693, 0.79938474,
        0.12088361, 0.32074169, 0.82628426, 0.60635327, 0.24390741,
        0.32615678, 0.86244742, 0.24893153, 0.92328903, 0.23840465,
        0.14403381, 0.7268851 , 0.83539397, 0.48675055, 0.53436309,
        0.633084  , 0.62792537, 0.16126607, 0.99616922, 0.54788501,
        0.57326428, 0.99641083, 0.61719278, 0.32436429, 0.54942971,
        0.15553189, 0.0788466 , 0.06820622, 0.02

In [11]:
z[:3,:3], z[:3,:3].ravel(), z[:3,:3].flatten()


(array([[0.11951592, 0.52452718, 0.17163764],
        [0.28318079, 0.07380053, 0.67700478],
        [0.28587904, 0.79406193, 0.72896436]]),
 array([0.11951592, 0.52452718, 0.17163764, 0.28318079, 0.07380053,
        0.67700478, 0.28587904, 0.79406193, 0.72896436]),
 array([0.11951592, 0.52452718, 0.17163764, 0.28318079, 0.07380053,
        0.67700478, 0.28587904, 0.79406193, 0.72896436]))

In [16]:
z = np.random.rand(3,3)
z

array([[0.46880307, 0.4044079 , 0.93580757],
       [0.0967918 , 0.1195298 , 0.86318903],
       [0.48905681, 0.99373712, 0.54131577]])

In [20]:
a = z[:3,:3].ravel()
b = z[:3,:3].flatten()

In [ ]:
np.may_share_memory(z, a) # Ravel shares memory!

True

In [ ]:
np.may_share_memory(z, b) # Flatten do not share memory!

False

In [ ]:
arr = np.ndarray(100) # Same as np.random.rand() -> which give ndadarray as output
arr

array([0.11951592, 0.52452718, 0.17163764, 0.88442747, 0.06137786,
       0.79213121, 0.2027002 , 0.84121977, 0.91072484, 0.20073507,
       0.28318079, 0.07380053, 0.67700478, 0.72035511, 0.87943068,
       0.29647927, 0.28925387, 0.87919524, 0.94030504, 0.84898947,
       0.28587904, 0.79406193, 0.72896436, 0.55794227, 0.76490174,
       0.5606896 , 0.97423891, 0.95803352, 0.11273432, 0.39664859,
       0.86059036, 0.79688046, 0.78497531, 0.43175944, 0.64595988,
       0.78482064, 0.52985417, 0.18770541, 0.97799868, 0.61801055,
       0.39028889, 0.21912466, 0.03391681, 0.03816693, 0.79938474,
       0.12088361, 0.32074169, 0.82628426, 0.60635327, 0.24390741,
       0.32615678, 0.86244742, 0.24893153, 0.92328903, 0.23840465,
       0.14403381, 0.7268851 , 0.83539397, 0.48675055, 0.53436309,
       0.633084  , 0.62792537, 0.16126607, 0.99616922, 0.54788501,
       0.57326428, 0.99641083, 0.61719278, 0.32436429, 0.54942971,
       0.15553189, 0.0788466 , 0.06820622, 0.02495186, 0.62152

In [ ]:
arr1 = arr.reshape(10,10) # Simple reshape
arr1

array([[0.11951592, 0.52452718, 0.17163764, 0.88442747, 0.06137786,
        0.79213121, 0.2027002 , 0.84121977, 0.91072484, 0.20073507],
       [0.28318079, 0.07380053, 0.67700478, 0.72035511, 0.87943068,
        0.29647927, 0.28925387, 0.87919524, 0.94030504, 0.84898947],
       [0.28587904, 0.79406193, 0.72896436, 0.55794227, 0.76490174,
        0.5606896 , 0.97423891, 0.95803352, 0.11273432, 0.39664859],
       [0.86059036, 0.79688046, 0.78497531, 0.43175944, 0.64595988,
        0.78482064, 0.52985417, 0.18770541, 0.97799868, 0.61801055],
       [0.39028889, 0.21912466, 0.03391681, 0.03816693, 0.79938474,
        0.12088361, 0.32074169, 0.82628426, 0.60635327, 0.24390741],
       [0.32615678, 0.86244742, 0.24893153, 0.92328903, 0.23840465,
        0.14403381, 0.7268851 , 0.83539397, 0.48675055, 0.53436309],
       [0.633084  , 0.62792537, 0.16126607, 0.99616922, 0.54788501,
        0.57326428, 0.99641083, 0.61719278, 0.32436429, 0.54942971],
       [0.15553189, 0.0788466 , 0.0682062

In [24]:
arr1 = arr.reshape(-1, 20) # Leave one dimension for numpy calcualtion
arr1.shape

(5, 20)

In [25]:
arr1 = arr.reshape(4,5,-1)
arr1.shape

(4, 5, 5)

In [33]:
y = np.arange(10)
y, y.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,))

In [ ]:
k = np.resize(y, 20)
k , k.shape, y.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 (20,),
 (10,))

In [ ]:
y1 = np.arange(10)
print(y1)
y1.resize(20) # There is a difference in np.resize and ndarray.resize
# np.resize fills additionally added cells with same data 
# ndarray.resize fills with 0
y1, y1.shape

[0 1 2 3 4 5 6 7 8 9]


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), (20,))

In [45]:
# With string array it works while filling with blanks
l = np.array(['a', 'b','c'])
print(l)
l.resize(10)
l

['a' 'b' 'c']


array(['a', 'b', 'c', '', '', '', '', '', '', ''], dtype='<U1')

In [ ]:
# Boolean fills with False
q = np.array([True, True, True])
print(q)
q.resize(10)
q

[ True  True  True]


array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
x, np.sort(x)[::-1] # Sort and then reverse

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
        82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
        65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
        48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
        14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]))